package com.innowise.userservice.model.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

/**
 * Represents a credit card information entity in the database.
 * This entity is mapped to the "card_info" table.
 */
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Entity
@Table(name = "card_info",
        indexes = {
                @Index(name = "idx_card_info_user_id", columnList = "user_id"),
                @Index(name = "idx_card_info_number", columnList = "number")
        })
public class CardInfo {

    /**
     * The unique identifier for the card.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The card number.
     * Max length 50. Cannot be null.
     */
    @Column(length = 50, nullable = false)
    private String number;

    /**
     * The name of the holder.
     * Max length 50. Cannot be null.
     */
    @Column(length = 50, nullable = false)
    private String holder;

    /**
     * The expiration date of the card. Cannot be null.
     */
    @Column(nullable = false)
    private LocalDate expirationDate;

    /**
     * The user who owns this card.
     * This is a many-to-one relationship.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

}
