apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-service-mongodb
spec:
  serviceName: payment-service-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-mongodb
  template:
    metadata:
      labels:
        app: payment-service-mongodb
    spec:
      containers:
        - name: payment-service-mongodb
          image: mongo:8.2.1
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-database
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
          volumeMounts:
            - name: payment-service-mongodb
              mountPath: /data/db
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "1000m"
              ephemeral-storage: "3Gi"
  volumeClaimTemplates:
    - metadata:
        name: payment-service-mongodb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi