apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongodb-uri: "mongodb://<mongodb-username>:<mongodb-password>@payment-service-mongodb:27017/paymentdb?authSource=admin"
  mongodb-database: paymentdb
  mongodb-username: CHANGE_ME
  mongodb-password: CHANGE_ME

