apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  user-db-name: userdb
  user-db-user: CHANGE_ME
  user-db-password: CHANGE_ME

  auth-db-name: authdb
  auth-db-user: CHANGE_ME
  auth-db-password: CHANGE_ME

  order-db-name: orderdb
  order-db-user: CHANGE_ME
  order-db-password: CHANGE_ME

